### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by Hengameh400** [yerfor/GeneFace#76]
Hi, 

Do you have any idea how to solve this error? note that to install torch-ngp, i followed this page:   https://github.com/ashawkey/torch-ngp

git clone --recursive https://github.com/ashawkey/torch-ngp.git
cd torch-ngp
pip install -r requirements.txt
pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch

The error is:

File "GeneFace/modules/radnerfs/renderer.py", line 318, in render
    weights_sum = torch.zeros(N, dtype=dtype, device=device)

RuntimeError: CUDA error: an illegal memory access was encountered

note that this is my torch version:

>>> import torch
>>> torch.__version__
'1.12.0'
>>>

many thanks.

**Comment by Hengameh400** [comment]
thanks for your reply. 
I did run bash docs/prepare_env/install_ext.sh

could you plz let me know your: torch.__version__

**Comment by Hengameh400** [comment]
also, I saw this note by you:

If you find any error in python package compatility, you can refer to docs/prepare_env/geneface_*.yaml for my tested specific package versions for different GPUs.

at my stage, could you plz guide how to use those yaml files in my end? which cmd I should use? /thx

**Comment by Hengameh400** [comment]
I run: conda env export > my_env.yaml 

"my_env.yaml"  
                                                                             1,1           Top
  name: geneface
  2 channels:
  3   - pytorch3d
  4   - pytorch
  5   - bottler
  6   - iopath
  7   - conda-forge
  8   - defaults
  9 dependencies:
 10   - _libgcc_mutex=0.1=main
 24   - giflib=5.2.1=h5eee18b_3
 25   - idna=3.4=py39h06a4308_0
 27   - iopath=0.1.9=py39
 28   - jpeg=9e=h5eee18b_1
 29   - lcms2=2.12=h3be6417_0
 30   - ld_impl_linux-64=2.38=h1181459_1
 31   - lerc=3.0=h295c915_0
 32   - libdeflate=1.17=h5eee18b_0
 33   - libffi=3.4.2=h6a678d5_6
 34   - libgcc-ng=11.2.0=h1234567_1
 35   - libgomp=11.2.0=h1234567_1
 36   - libpng=1.6.39=h5eee18b_0
 37   - libstdcxx-ng=11.2.0=h1234567_1
38   - libtiff=4.5.0=h6a678d5_2
 39   - libwebp=1.2.4=h11a3e52_1
 50   - openssl=1.1.1t=h7f8727e_0
 51   - pillow=9.4.0=py39h6a678d5_0
 52   - pip=23.0.1=py39h06a4308_0
 53   - portalocker=2.7.0=py39hf3d152e_0
 54   - pycparser=2.21=pyhd3eb1b0_0
 55   - pyopenssl=23.0.0=py39h06a4308_0
 56   - pysocks=1.7.1=py39h06a4308_0
 57   - python=3.9.16=h7a1cb2a_2
 58   - python_abi=3.9=2_cp39
 59   - pytorch=1.12.0=py3.9_cuda11.3_cudnn8.3.2_0
 60   - pytorch-mutex=1.0=cuda
 61   - pytorch3d=0.7.2=py39_cu113_pyt1120
 62   - pyyaml=6.0=py39hb9d737c_4
 63   - readline=8.2=h5eee18b_0
 64   - requests=2.28.1=py39h06a4308_1
 65   - setuptools=65.6.3=py39h06a4308_0
 66   - six=1.16.0=pyhd3eb1b0_1
 67   - sqlite=3.41.1=h5eee18b_0
 68   - tabulate=0.9.0=pyhd8ed1ab_1
 69   - termcolor=2.2.0=pyhd8ed1ab_0
 70   - tk=8.6.12=h1ccaba5_0
 71   - torchvision=0.13.1=cpu_py39h164cc8f_0
 72   - tqdm=4.65.0=pyhd8ed1ab_1
 73   - typing_extensions=4.4.0=py39h06a4308_0
 74   - tzdata=2022g=h04d1e81_0
74   - tzdata=2022g=h04d1e81_0
 75   - urllib3=1.26.14=py39h06a4308_0
 76   - wheel=0.38.4=py39h06a4308_0
 77   - xz=5.2.10=h5eee18b_1
 78   - yacs=0.1.8=pyhd8ed1ab_0
 79   - yaml=0.2.5=h7f98852_2
 80   - zlib=1.2.13=h5eee18b_0
 81   - zstd=1.5.2=ha4553b6_0
 82   - pip:
 83     - absl-py==1.4.0
 84     - appdirs==1.4.4
 85     - astunparse==1.6.3
 86     - audioread==3.0.0
 87     - cachetools==5.3.0
 88     - configargparse==1.5.3
 89     - contourpy==1.0.7
 90     - cycler==0.11.0
 91     - dearpygui==1.8.0
 92     - decorator==4.4.2
 93     - dominate==2.7.0
 94     - face-alignment==1.3.5
 95     - ffmpeg-python==0.2.0
 96     - filelock==3.10.0
 97     - flatbuffers==23.3.3
 98     - fonttools==4.39.2
 99     - freqencoder==0.0.0
100     - future==0.18.3
101     - gast==0.4.0
102     - google-auth==2.16.2
103     - google-auth-oauthlib==0.4.6
104     - google-pasta==0.2.0
105     - gridencoder==0.0.0
106     - grpcio==1.51.3
107     - h5py==3.8.0
108     - huggingface-hub==0.13.3
109     - imageio==2.26.1
110     - imageio-ffmpeg==0.4.8
110     - imageio-ffmpeg==0.4.8
111     - importlib-metadata==6.1.0
112     - importlib-resources==5.12.0
113     - joblib==1.2.0
114     - keras==2.11.0
115     - kiwisolver==1.4.4
116     - kornia==0.6.10
117     - lazy-loader==0.2
118     - libclang==15.0.6.1
119     - librosa==0.10.0.post2
120     - llvmlite==0.39.1
121     - lpips==0.1.4
122     - markdown==3.4.1
123     - markupsafe==2.1.2
124     - matplotlib==3.7.1
125     - moviepy==1.0.3
126     - msgpack==1.0.5
127     - networkx==3.0
128     - ninja==1.11.1
129     - numba==0.56.4
130     - oauthlib==3.2.2
131     - opencv-python==4.7.0.72
132     - opt-einsum==3.3.0
133     - packaging==23.0
134     - pandas==1.5.3
135     - pooch==1.6.0
136     - praat-parselmouth==0.4.3
137     - proglog==0.1.10
138     - protobuf==3.19.6
139     - pyasn1==0.4.8
140     - pyasn1-modules==0.2.8
141     - pyaudio==0.2.13
142     - pymcubes==0.1.4
143     - pyparsing==3.0.9
144     - python-dateutil==2.8.2
145     - python-speech-features==0.6
145     - python-speech-features==0.6
146     - pytz==2022.7.1
147     - pywavelets==1.4.1
148     - raymarching-face==0.0.0
149     - regex==2022.10.31
150     - requests-oauthlib==1.3.1
151     - resampy==0.4.2
152     - rsa==4.9
153     - scikit-image==0.20.0
154     - scikit-learn==1.2.2
155     - scipy==1.9.1
156     - shencoder==0.0.0
157     - soundfile==0.12.1
158     - soxr==0.3.4
159     - tensorboard==2.11.2
160     - tensorboard-data-server==0.6.1
161     - tensorboard-plugin-wit==1.8.1
162     - tensorboardx==2.6
163     - tensorflow==2.11.0
164     - tensorflow-estimator==2.11.0
165     - tensorflow-io-gcs-filesystem==0.31.0
166     - threadpoolctl==3.1.0
167     - tifffile==2023.3.15
168     - tokenizers==0.13.2
169     - transformers==4.27.2
170     - trimesh==3.21.0
171     - werkzeug==2.2.3
172     - wrapt==1.15.0
173     - zipp==3.15.0

**Comment by yerfor** [comment]
you can try "conda env create -f <env.yaml>"

**Comment by Hengameh400** [comment]
cool. let me try. I truly appreciate your prompt responses.

**Comment by Hengameh400** [comment]
I tried both 
conda env create -f geneface_rtx2080.yaml
conda env create -f geneface_rtx3090.yaml

and still get `RuntimeError: CUDA error: an illegal memory access was encountered` 

any other suggestion? /thx

**Comment by Hengameh400** [comment]
could you plz guide how to try smaller batch_size? on which yml file?

note that I could successfuly run --config lm3d_postnet_sync.yaml
the above error occured when I run --config lm3d_radnerf.yaml

maybe I should try smaller batch_size. I am not sure on which yaml file I can conrol batch_size 

thanks

**Comment by Hengameh400** [comment]
egs/egs_bases/radnerf/base.yaml

should I change>> max_ray_batch: 4096 #

**Comment by Hengameh400** [comment]
it seems that this line of code https://github.com/yerfor/GeneFace/blob/main/modules/radnerfs/raymarching/raymarching.py#L44 is problematic to me. 

After running L44, when e.g. I want to do check or set some torch pars, that error is occured.

**Comment by Hengameh400** [comment]
# make sure your cuda path (typically /usr/local/cuda) points to a installed `/usr/local/cuda-11.3`

you mentioned the above. Maybe that is the reason. could you plz guide me how to take care of the above comment by you. thx

**Comment by Hengameh400** [comment]
also, could you please guide what is happening on this function:        _backend.near_far_from_aabb(rays_o, rays_d, aabb, N, min_near, nears, fars)
 

how I should interpret it? can I simply comment it? sorry if my question is very trivial. I want to learn. thanks.

**Comment by Hengameh400** [comment]
similar things is happening here: https://github.com/yerfor/GeneFace/blob/main/modules/radnerfs/encoders/gridencoder/grid.py#L54

**Comment by Hengameh400** [comment]
summary of my findings: when I comment these two lines [L44](https://github.com/yerfor/GeneFace/blob/main/modules/radnerfs/raymarching/raymarching.py#L44) and [L54](https://github.com/yerfor/GeneFace/blob/main/modules/radnerfs/encoders/gridencoder/grid.py#L54), the rest of the code is fine. Now, I want to learn what is happening on these _backend functions and how to fix the issue. I would appreciate your kind help in this regard. /thanks

**Comment by Hengameh400** [comment]
try:
    import _gridencoder as _backend
except ImportError:
    from .backend import _backend

in my case, >>  *from .backend import _backend* is passed. Could you plz guide what is `_gridencoder`?



try:
    import _raymarching_face as _backend
except ImportError:
    from .backend import _backend

in my case: >> *import _raymarching_face as _backend* is passed

**Comment by yerfor** [comment]
> # make sure your cuda path (typically /usr/local/cuda) points to a installed `/usr/local/cuda-11.3`
> you mentioned the above. Maybe that is the reason. could you plz guide me how to take care of the above comment by you. thx

Hi, To do this, you should locally install cuda (not with conda), you can refer to the [official link](https://developer.nvidia.com/cuda-11-3-1-download-archive). Download the .runfile and make sure the installed cuda path is `/usr/local/cuda`

**Comment by Hengameh400** [comment]
could you plz kindly guide me on those _backend functions (which I listed above). what is happening on those functions? they are not python function; can I simply comment them? if not, can I replace them with a python function somehow, which is easy for me to debug. 

many thanks.

**Comment by yerfor** [comment]
No, this functions are CUDA extensions and they are expected to run on the installed CUDA located at `/usr/local/cuda`. It is not easy to replace them with python code, because they are implemented in cuda(see files located at `src/*.cu`). 

Therefore, I recommend you to install the CUDA correctly, which may help you out.

**Comment by Hengameh400** [comment]
I run bash docs/prepare_env/install_ext.sh; based on the following log, it seems that it run successfully. 

Then, when I run e.g. `import _raymarching_face as _backend`, _backend should be imported from `_raymarching_face`, right?

Processing ./modules/radnerfs/encoders/freqencoder
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: freqencoder
  Building wheel for freqencoder (setup.py) ... done
  Created wheel for freqencoder: filename=freqencoder-0.0.0-cp39-cp39-linux_x86_64.whl size=67123 sha256=3f000dcd300be8a9584809b0d456cbc01ddd5a72b67282f7175ae63dd37e7df9
  Stored in directory: /tmp/pip-ephem-wheel-cache-fggtupmu/wheels/25/66/f9/62693f85380b197c75c47fa19ab81ace687a0583afe70fbf86
Successfully built freqencoder

Successfully installed freqencoder-0.0.0
Processing ./modules/radnerfs/encoders/shencoder
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: shencoder
  Building wheel for shencoder (setup.py) ... done
  Created wheel for shencoder: filename=shencoder-0.0.0-cp39-cp39-linux_x86_64.whl size=134048 sha256=2cb2fa9ef8e8f097870e2fc4def0eb54d99de621d7245f18ffb6595ca4257ed3
  Stored in directory: /tmp/pip-ephem-wheel-cache-spnj_syx/wheels/e7/27/35/4f19b6c157bce0e9b33d985af5cd00b2d376f98dda612471f2
Successfully built shencoder
Installing collected packages: shencoder
Successfully installed shencoder-0.0.0
Processing ./modules/radnerfs/encoders/gridencoder
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: gridencoder
  Building wheel for gridencoder (setup.py) ... |                                                                                                                            done
  Created wheel for gridencoder: filename=gridencoder-0.0.0-cp39-cp39-linux_x86_64.whl size=3788644 sha256=ed70cbaab9b48dbb77ae1370da10248c2c12158e6ac1b8888e5677f3254e9af4
  Stored in directory: /tmp/pip-ephem-wheel-cache-675lompr/wheels/f5/8f/92/9cfbcfb44ab716f249b7b31a757d1b3467dc2a1c1e378b92ea
Successfully built gridencoder
Installing collected packages: gridencoder
Successfully installed gridencoder-0.0.0
Processing ./modules/radnerfs/raymarching
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: raymarching-face
  Building wheel for raymarching-face (setup.py) ... |
 * Ubuntu Pro delivers the most comprehensive open source security and
   compliance features.

   https://ubuntu.com/aws/pro

 * Introducing Expanded Security Maintenance for Applications.
   Receive updates to over 25,000 software packages with your
Successfully built shencoder
Installing collected packages: shencoder
Successfully installed shencoder-0.0.0
Processing ./modules/radnerfs/encoders/gridencoder
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: gridencoder
  Building wheel for gridencoder (setup.py) ... |                                                                                                                            done
  Created wheel for gridencoder: filename=gridencoder-0.0.0-cp39-cp39-linux_x86_64.whl size=3788644 sha256=ed70cbaab9b48dbb77ae1370da10248c2c12158e6ac1b8888e5677f3254e9af4
  Stored in directory: /tmp/pip-ephem-wheel-cache-675lompr/wheels/f5/8f/92/9cfbcfb44ab716f249b7b31a757d1b3467dc2a1c1e378b92ea
Successfully built gridencoder
Installing collected packages: gridencoder
Successfully installed gridencoder-0.0.0
Processing ./modules/radnerfs/raymarching
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: raymarching-face
  Building wheel for raymarching-face (setup.py) ... |
Successfully built shencoder
Installing collected packages: shencoder
Successfully installed shencoder-0.0.0
Processing ./modules/radnerfs/encoders/gridencoder
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: gridencoder
  Building wheel for gridencoder (setup.py) ... |                                                                                                                            done
  Created wheel for gridencoder: filename=gridencoder-0.0.0-cp39-cp39-linux_x86_64.whl size=3788644 sha256=ed70cbaab9b48dbb77ae1370da10248c2c12158e6ac1b8888e5677f3254e9af4
  Stored in directory: /tmp/pip-ephem-wheel-cache-675lompr/wheels/f5/8f/92/9cfbcfb44ab716f249b7b31a757d1b3467dc2a1c1e378b92ea
Successfully built gridencoder
Installing collected packages: gridencoder
Successfully installed gridencoder-0.0.0
Processing ./modules/radnerfs/raymarching
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: raymarching-face
  Building wheel for raymarching-face (setup.py) ... done
  Created wheel for raymarching-face: filename=raymarching_face-0.0.0-cp39-cp39-linux_x86_64.whl size=174318 sha256=571c2eba839e006d4ff99e62de76a14a05840454b34ea431b4fe55c94be0672d
  Stored in directory: /tmp/pip-ephem-wheel-cache-y2spii7o/wheels/d3/06/cf/74c7366a9380c2875973402b0893866265a3bed0d2bdbbbc1c
Successfully built raymarching-face
Installing collected packages: raymarching-face
Successfully installed raymarching-face-0.0.0

**Comment by Hengameh400** [comment]
this is what I get after runing import _raymarching_face as _backend

[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _raymarching_face as _backend
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libc10.so: cannot open shared object file: No such file or directory

**Comment by Hengameh400** [comment]
I did checkout all my changes and try to debug from the begging. 

I found that, although i have one gpu, self.all_gpu_ids  [[here](https://github.com/yerfor/GeneFace/blob/main/utils/commons/trainer.py#L98)] is []

         self.all_gpu_ids = [
            int(x) for x in os.environ.get("CUDA_VISIBLE_DEVICES", "").split(",") if x != '']
       
!

**Comment by Hengameh400** [comment]
I hardcode  self.all_gpu_ids  and it seems that it is running and this problem is solved.

**Comment by Hengameh400** [comment]
:'(

I do not want to loose my hope to be able to run your code. 

But, after redoing everything, when I start to train /lm3d_radnerf.yaml, 

[here](https://github.com/yerfor/GeneFace/blob/main/utils/commons/base_task.py#L71), I got this error:

>> self.logger = SummaryWriter(log_dir=log_dir, **kwargs)

```
2023-03-30 23:14:01.581882: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[libprotobuf FATAL google/protobuf/stubs/common.cc:83] This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.19.6).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
Aborted (core dumped)
```

my first env, was created using: pip install -r docs/prepare_env/requirements.txt 
after I got the above error, I remove it and use  geneface_rtx2080.yaml to create geneface env.

:'( :'( :'(

**Comment by Hengameh400** [comment]
I add 
>>from torch.utils.tensorboard import SummaryWriter
>>SummaryWriter(log_dir='.', **{})

at run.py right above [L9](https://github.com/yerfor/GeneFace/blob/main/tasks/run.py#L9) ; then, the code will not give me the error above. I have zero idea why this is the case. Not sure how much it affect things. for now, I can see the traning log. 

I am hoping to get some results similar to what you shared above [finger crossed]
